# -*- coding: utf-8 -*-
"""IPL visulaization Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cd0iiGNTzisy4ytWXiOJ2xXhwnyhXdV
"""

#Loading the libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df=pd.read_csv("IPL.csv") #read csv file
df

df.head() #top 5 rows

df.tail() #bottom 5 rows

df.shape

df.columns

df.info()   #finding information about dataset

df.describe() #statistical information

#fining null values
df.isnull().sum()

#which team won the most matches ?
matches_wins=df['match_winner'].value_counts()
matches_wins

sns.barplot(y=matches_wins.index,x=matches_wins.values,palette="rainbow")
plt.title("Matches won by each team")
plt.show()

"""Toss Decision

"""

#count the toss decision
sns.countplot(x=df['toss_decision'],palette="deep")
plt.title("Toss Decision")
plt.show()

count=df[df["toss_winner"]==df["match_winner"]]["match_id"].count()
percentage=(count*100)/df.shape[0]
print("Winning percentage if you won the toss=",percentage.round(2),"%")

#count , how the team wins (Runs vs Wickets)

sns.countplot(x=df["won_by"])
plt.title("Won by")

df.head()

#finding most player of the match awards
count=df["player_of_the_match"].value_counts().head(10)
print(count)

sns.barplot(x = count.values , y = count.index,palette='rainbow')
plt.title("Top 10 plauers with man of the match")

#explain
# top_scorer               highscore
# virat                        120
# rohit                        100
# virat                        150
# dhoni                         90
# rohit                         110


# df.groupby("top_scorer")
# virat:120,120
# rohit:100,110
# dhoni:90

# df.groupby("top_scorer")[highscore].sum()
# virat=270
# rohit=210
# dhoni=90

high=df.groupby("top_scorer")["highscore"].sum().sort_values(ascending=False).head(2)
print(high)

high.plot(kind="bar")

high.plot(kind="barh")

df.head()

# # best_bowling             best_bowling_figure
# # Chahal                       5--40
# # chahal                       3--25
# # Bumrah                       4--18
# # Rashid                       2--15


# apply()  - it executes a function on every row

# 1.split using
# 2.Take first part


# "5--40".split("--")[0]
# #output - ["5","40"]
# #output - 5


# "3--25".split("--")[0]
# #output - ["3","25"]
# #output - 3

# ...........


# new column created
# highest_wickets                 best_bowling_figure
#       5                             5--40
#       3                             3--25
#       4                             4--18
#       2                             2--15


#   .astype(int)

df["highest_wickets"]=df["best_bowling_figure"].apply(lambda x:x.split("--")[0])
df["highest_wickets"]=df["highest_wickets"].astype(int)
top_bowlers=df.groupby("best_bowling")["highest_wickets"].sum().sort_values(ascending=False).head(10)
top_bowlers.plot(kind="barh")

df

#Most matches played in which venue ???
venue_count=df["venue"].value_counts()
venue_count

sns.barplot(y=venue_count.index,x=venue_count.values,palette="rainbow")
plt.title("Matches played in each venue")
plt.show()

"""**Questions and Answers ??????**

**Who won the highest margin by runs?**
"""

df

# Example
# Match                won_by
# 1                      runs
# 2                      Wickets
# 3                      runs

# step1:- filter matches won by runs
#  df["won_by"]=="Runs"
#  result = T ,F ,T

#  GT              runs      65 = margin
#  Chennai         runs      50
#  Mumbai          runs      65


# Step-2 sort by margin

# .sort_values(by="margin",ascending=False).head(1)

df[df["won_by"]=="Runs"].sort_values(by="margin",ascending=False).head(1)[["match_winner","margin"]]

#Top 5 By Margin
df[df["won_by"]=="Runs"].sort_values(by="margin",ascending=False).head(5)[["match_winner","margin"]]

#Bottom 5 By Margin
df[df["won_by"]=="Runs"].sort_values(by="margin",ascending=False).tail(5)[["match_winner","margin"]]

"""**Which player had the highest individual score?**"""

#example
# top_scorer                  highscore
# KL rahul                      103
# jos buttler                    116
# faf                           96
# dhoni                          140

# df["highscore"]==df["highscore"].max()

#   140

df[df['highscore']==df['highscore'].max()][["top_scorer","highscore"]]

"""**Which bowler had the best bowling figure**"""

df

df[df["highest_wickets"]==df["highest_wickets"].max()][["best_bowling","best_bowling_figure"]]

"""**Team Performance Questions**

**Which team won the most matches?**
"""

df

df["match_winner"].value_counts().head(1)

